[project]
name = "dwg-metrics-explorer"
version = "0.1.0"
description = "Extrair metricas de arquivos dwg"
authors = [
    {name = "Lucas Gabriel de Almeida",email = "156014432+LucasG-Alm@users.noreply.github.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas (>=2.2.3,<3.0.0)",
    "tqdm (>=4.67.1,<5.0.0)",
    "ezdxf (>=1.4.1,<2.0.0)",
    "numpy (>=2.2.5,<3.0.0)",
    "streamlit (>=1.44.1,<2.0.0)",
    "xlsxwriter (>=3.2.3,<4.0.0)",
    "plotly (>=6.0.1,<7.0.0)"
]

[tool.poetry]

[tool.poetry.group.dev.dependencies]
pandas = "^2.2.3"
tqdm = "^4.67.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
